name: Build & Release PrestaShop Module

on:
  push:
    tags:
      - 'v*'   # runs only when you push a tag like v1.0.0

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare PrestaShop ZIP
        run: |
          mkdir -p package/paymentpayee
          shopt -s dotglob
          for f in *; do
            [ "$f" = "package" ] && continue
            mv "$f" package/paymentpayee/
          done
          cd package
          zip -r paymentpayee.zip paymentpayee \
            -x '*.git*' '*.github*' '*/tests/*' '*/docs/*'
          mv paymentpayee.zip ../ \
          cd ..

      - name: Delete old assets
        run: |
          assets=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.release_info.outputs.id }}/assets \
            | jq -r '.[].id')
          for asset_id in $assets; do
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/assets/$asset_id
          done

      - name: Publish to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: paymentpayee.zip
          asset_name: paymentpayee.zip
          asset_content_type: application/zip
