name: Build & Release PrestaShop Module

on:
  push:
  workflow_dispatch:   # allows manual trigger from GitHub UI

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare PrestaShop ZIP
        run: |
          mkdir -p package/paymentpayee
          shopt -s dotglob
          mv * package/paymentpayee/
          cd package
          zip -r paymentpayee.zip paymentpayee \
            -x '*.git*' '*.github*' '*/tests/*' '*/docs/*'
          mv paymentpayee.zip ../

      - name: Publish to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          asset_path: ./paymentpayee.zip
          asset_name: paymentpayee.zip
          asset_content_type: application/zip
