name: Build & Release PrestaShop Module

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare paymentpayee.zip
        run: |
          mkdir -p package/paymentpayee
          shopt -s dotglob
          for f in *; do
            [ "$f" = "package" ] && continue
            mv "$f" package/paymentpayee/
          done
          cd package
          zip -r paymentpayee.zip paymentpayee \
            -x '*.git*' '*.github*' '*/tests/*' '*/docs/*'
          mv paymentpayee.zip ../

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./paymentpayee.zip
          asset_name: paymentpayee.zip
          asset_content_type: application/zip


